const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    PLAY_MUSIC: "PLAY_MUSIC",
    SET_ALBUM: "SET_ALBUM",
    PLAYLIST: "PLAYLIST",
    LOADING: "LOADING",
    SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
    SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
    SET_RECENT: "SET_RECENT",
    SEARCH: "SEARCH",
};
export default actionTypes;
